export const TypesEnum = {
  Normal: "Normal",
  Fire: "Fire",
  Fighting: "Fighting",
  Water: "Water",
  Flying: "Flying",
  Grass: "Grass",
  Poison: "Poison",
  Electric: "Electric",
  Ground: "Ground",
  Psychic: "Psychic",
  Rock: "Rock",
  Ice: "Ice",
  Bug: "Bug",
  Dragon: "Dragon",
  Ghost: "Ghost",
  Dark: "Dark",
  Steel: "Steel",
  Fairy: "Fairy",
};
